name: deploy blog
on:
  push:
    branches:
      - main
jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Clean and Reinstall
        run: |
          rm -rf node_modules
          npm cache clean --force
          npm install --force
      
      - name: Install Hexo
        run: |
          npm install hexo-cli -g
          npm install hexo --save
      
      - name: Generate Site
        run: |
          npx hexo clean
          npx hexo generate
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          full_commit_message: ${{ github.event.head_commit.message }}